#!/bin/bash

clear
#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$Y"
repo_cust(){
read -p "Install Custom Repo, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Memasang Custom Repo"
sleep 2
clear
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf
echo "src/gz custom_generic https://raw.githubusercontent.com/lrdrdn/my-opkg-repo/main/generic" >> /etc/opkg/customfeeds.conf
echo "src/gz custom_arch https://raw.githubusercontent.com/lrdrdn/my-opkg-repo/main/$(cat /etc/os-release | grep OPENWRT_ARCH | awk -F '"' '{print $2}')" >> /etc/opkg/customfeeds.conf
echo "src/gz custom_minimal https://raw.githubusercontent.com/lrdrdn/my-opkg-repo/main/minimal" >> /etc/opkg/customfeeds.conf
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
PLite_Mipsel_24kc_16MB(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Mulai installasi Passwall lite"
sleep 2
clear
opkg remove dnsmasq && opkg update && opkg install dnsmasq-full ipset ipt2socks iptables iptables-legacy iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat luci-compat
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/luci-app-passwall_lite_all.ipk" -O /tmp/luci-app-passwall_lite_all.ipk && chmod +x /tmp/luci-app-passwall_lite_all.ipk && cd /tmp && opkg update && opkg install *.ipk && rm /tmp/luci-app-passwall_lite_all.ipk
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/xray" -O /usr/bin/xray && chmod +x /usr/bin/xray
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/status.htm"  -O /usr/lib/lua/luci/view/passwall/global/status.htm && chmod +x /usr/lib/lua/luci/view/passwall/global/status.htm
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/passwall.lua" -O /usr/lib/lua/luci/controller/passwall.lua && chmod +x /usr/lib/lua/luci/controller/passwall.lua
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
PLite_All(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Mulai installasi Passwall lite"
sleep 2
clear
opkg remove dnsmasq && opkg update && opkg install dnsmasq-full ipset ipt2socks iptables iptables-legacy iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat luci-compat xray-core trojan-go
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/luci-app-passwall_lite_all.ipk" -O /tmp/luci-app-passwall_lite_all.ipk && chmod +x /tmp/luci-app-passwall_lite_all.ipk && cd /tmp && opkg update && opkg install *.ipk && rm /tmp/luci-app-passwall_lite_all.ipk
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/status.htm"  -O /usr/lib/lua/luci/view/passwall/global/status.htm && chmod +x /usr/lib/lua/luci/view/passwall/global/status.htm
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/main/passwall.lua" -O /usr/lib/lua/luci/controller/passwall.lua && chmod +x /usr/lib/lua/luci/controller/passwall.lua
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}

banner(){
clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG INSTALLER PASSWALL LITE      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y     PILIH ARCH SESUAI DEVICE YANG DIPAKAI!!!     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G SCRIPT REPO                        * sh inpass 1 $DB**"
echo -e "$DB **$G INSTALL PASSWALL 16MB MIPSEL_24KC  * sh inpass 2 $DB**"
echo -e "$DB **$G INSTALL PASSWALL ALL ARCH          * sh inpass 3 $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y      INSTALLER PASSWALL LITE BY ALKHANET         $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
}

case $1 in
"1")
repo_cust;exit
;;
esac

case $1 in
"2")
PLite_Mipsel_24kc_16MB;exit
;;
esac

case $1 in
"3")
PLite_All;exit
;;
esac


clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG INSTALLER PASSWALL LITE      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y     PILIH ARCH SESUAI DEVICE YANG DIPAKAI!!!     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G SCRIPT REPO                        * sh inpass 1 $DB**"
echo -e "$DB **$G INSTALL PASSWALL 16MB MIPSEL_24KC  * sh inpass 2 $DB**"
echo -e "$DB **$G INSTALL PASSWALL ALL ARCH          * sh inpass 3 $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y      INSTALLER PASSWALL LITE BY ALKHANET         $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
exit
