#!/bin/bash

clear
#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$Y"
repo_cust(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Memasang Custom Repo"
sleep 2
clear
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/cfeed.sh" -O /tmp/cfeed.sh && chmod +x /tmp/cfeed.sh && cd /tmp/sh cfeed.sh && rm /tmp/cfeed.sh
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
PLite_Mipsel_24kc_16MB(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Mulai installasi Passwall lite"
sleep 2
clear
opkg update && opkg install ipset ipt2socks iptables iptables-legacy iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat coreutils coreutils-base64 coreutils-nohup curl dns2socks ip-full libuci-lua lua luci-compat luci-lib-jsonc microsocks resolveip tcping unzip
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/luci-app-passwall_4.51_all_.ipk" -O /tmp/luci-app-passwall_4.51_all_.ipk && chmod +x /tmp/luci-app-passwall_4.51_all_.ipk && cd /tmp && opkg update && opkg install *.ipk && rm /tmp/luci-app-passwall_4.51_all_.ipk
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/mipsel_24kc/1/usr/bin/xray" -O /usr/bin/xray && chmod +x /usr/bin/xray
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/mipsel_24kc/1/usr/status/status.htm"  -O /usr/lib/lua/luci/view/passwall/global/status.htm && chmod +x /usr/lib/lua/luci/view/passwall/global/status.htm
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/passwall.lua" -O /usr/lib/lua/luci/controller/passwall.lua && chmod +x /usr/lib/lua/luci/controller/passwall.lua
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
PLite_Mipsel_24kc(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Mulai installasi Passwall lite"
sleep 2
clear
opkg update && opkg install ipset ipt2socks iptables iptables-legacy iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat coreutils coreutils-base64 coreutils-nohup curl dns2socks ip-full libuci-lua lua luci-compat luci-lib-jsonc microsocks resolveip tcping unzip
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/luci-app-passwall_4.51_all_.ipk" -O /tmp/luci-app-passwall_4.51_all_.ipk && chmod +x /tmp/luci-app-passwall_4.51_all_.ipk && cd /tmp && opkg update && opkg install *.ipk && rm /tmp/luci-app-passwall_4.51_all_.ipk
opkg update && opkg install xray-core trojan-go
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/mipsel_24kc/1/usr/status/status.htm"  -O /usr/lib/lua/luci/view/passwall/global/status.htm && chmod +x /usr/lib/lua/luci/view/passwall/global/status.htm
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/passwall.lua" -O /usr/lib/lua/luci/controller/passwall.lua && chmod +x /usr/lib/lua/luci/controller/passwall.lua
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}
echo -e "$Y"
Plite_stb_s905x(){
read -p "Install Passwall Lite, Anda Yakin? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo -e "Mulai installasi Passwall lite"
sleep 2
clear
opkg update && opkg install ipset ipt2socks iptables iptables-legacy iptables-mod-iprange iptables-mod-socket iptables-mod-tproxy kmod-ipt-nat coreutils coreutils-base64 coreutils-nohup curl dns2socks ip-full libuci-lua lua luci-compat luci-lib-jsonc microsocks resolveip tcping unzip
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/luci-app-passwall_4.51_all_.ipk" -O /tmp/luci-app-passwall_4.51_all_.ipk && chmod +x /tmp/luci-app-passwall_4.51_all_.ipk && cd /tmp && opkg update && opkg install *.ipk && rm /tmp/luci-app-passwall_4.51_all_.ipk
opkg update && opkg install xray-core trojan-go
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/aarch64_cortex-a53/usr/status/status.htm"  -O /usr/lib/lua/luci/view/passwall/global/status.htm && chmod +x /usr/lib/lua/luci/view/passwall/global/status.htm
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/plite/tree/main/plite/passwall.lua" -O /usr/lib/lua/luci/controller/passwall.lua && chmod +x /usr/lib/lua/luci/controller/passwall.lua
sleep 2
else
clear
echo -e "kembali ke halaman awal..."
sleep 2
clear
exit
fi
}

banner(){
clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG INSTALLER PASSWALL LITE      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y     PILIH ARCH SESUAI DEVICE YANG DIPAKAI!!!     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G SCRIPT REPO                        *     in1     $DB**"
echo -e "$DB **$G INSTALL PASSWALL 16MB MIPSEL_24KC  *     in2     $DB**"
echo -e "$DB **$G INSTALL PASSWALL >32MB MIPSEL_24KC *     in3     $DB**"
echo -e "$DB **$G INSTALL PASSWALL STB AMLOGIC       *     in4     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y      INSTALLER PASSWALL LITE BY ALKHANET         $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
}

case $1 in
"1")
repo_cust;exit
;;
esac

case $1 in
"2")
PLite_Mipsel_24kc_16MB;exit
;;
esac

case $1 in
"3")
PLite_Mipsel_24kc;exit
;;
esac

case $1 in
"4")
Plite_stb_s905x;exit
;;
esac


clear
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R      SELAMAT DATANG INSTALLER PASSWALL LITE      $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y     PILIH ARCH SESUAI DEVICE YANG DIPAKAI!!!     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        DAFTAR :                    *  PERINTAH : $DB**"
echo -e "$DB **$G SCRIPT REPO                        *     in1     $DB**"
echo -e "$DB **$G INSTALL PASSWALL 16MB MIPSEL_24KC  *     in2     $DB**"
echo -e "$DB **$G INSTALL PASSWALL >32MB MIPSEL_24KC *     in3     $DB**"
echo -e "$DB **$G INSTALL PASSWALL STB AMLOGIC       *     in4     $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y      INSTALLER PASSWALL LITE BY ALKHANET         $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
exit
